language: php
php:
- 5.4
env:
  global:
  - secure: DUMxo4YfCG7IXc/uMurlDZ0yjYEbFM5Abcvqn9sNmGeHnUoSD3fw5RP9S2l7FL2q3YpaQePqfUxv2ZFYkf8pkUKS7YgxYPOjOdbilY3srFyztOWtPqTK5lqcEBsdBh9XrcTbG1vyFMngXmk9aewA4i7TNVmu4RHOh0VX0wNOiWDVVdFSiK2iNXiY1oWyOpVi+LVQhLiEY/p0fAF37b15nfhyh+zYJfeUyK/dQL1soGqBCKBL+C1dpt4bR5kFIFhVbyO8i6b9Sq7ZGqZkSXN1TjzrOnlGK7FL9/i2lbTBdYIMDYZNOapNmeB2/iT+YzrFx3EZ7x4JL3Fqp8dY/iWtwstQsVCsuW6sigkhZ0vMGce8tV9l2DTmXJxLpj0BZ4b2AuhU0p22zVMX/SaynmJ2YBYDvOXmjru6hFA/VFGLWODyJdREKl3NreFoQTjvNqcCg95eUnJZtmM75yRaNSoShdYTVnfuPc9xXmvWGKgCXBPkBDQJiQhAOWMtYIGsRFOktoIDVneSx4pUaMfu4SAbYLN5Ze9mVaYQzyy4IEMl+0oT/nJeN6l+DP/68T5yNFgnJR5yohqqorOP11uJuZPQf8y1223Wsj9vdDkhRNhzcCoE0n64Txumn3FQE+LILYpceaGLzKte3Od4VgGljwdz0BJTdpwhmSSuIkm/vbh+/g8=
  - secure: hEdBgduhINJUFRkZ8pEoOvQvYaeCjhthb/TXXvSRd9ooe0nWFoNeijzs+tb2wzkqTKDNiKAudcixw0DKuMqpizVIvD5LMXJ9UayH/Q7Ctx1t8sUEdgrXzuxLirLCOYyGZp2bE+xpYGhuw9gVmdylJAJkOwfxKAd441u4XYt5uRvPiQzEH0X6d3aCxcjtXOf3GjfbpDktUatB596vo7msbubO+4BwDGw5KAJgsW/e4xGZOgMDSTfcL6sfo7ufDBCbwbFyt3Sjw7+hvB9JnVbcJRQv3ijawgyvJLRdsL2EHdOUW15EK7tMW+ngDWpqc1g9rhqcqKNmbN77CXf3F1jH6W3vgNTkNFaSzWGq8X293+zoOUvC+ugrvJcvqRpKk19kVAnqyFXGYh+eQfDBQNOyaHIAocwABdKJ7u7+4p8C8vCcNbb+ORCHYz1l5jURgjY4remxqpnH1NEtGOkvFHEVgpTAkPsr+HOwuWOss8UxwED43IQZXb8U7dEvZwUqaqYO/FWhcxJDopRD1VjlElIg1Ta06zN++ItUrQ6OLqSd5dRzF92XtOKII3VQMTs5UsTK0cqDiHcFN0dXOyy5ljX57vPoMFkuHe5yYLhcaVfH5OfhKHDfQHEciOhOSnbVt84qlDL9Q57CEiToanld1QUs1hh5zin97O0EWfE6Bm0nvdU=
script:
- ls
before_deploy:
- npm install gulp
- npm install gulp -g
- npm install vinyl-ftp gulp-util minimist --save-dev
deploy:
  skip_cleanup: true
  provider: script
  script: gulp deploy --user $FTP_USER --password $FTP_PASSWORD
  on:
    tags: true
